[package]
name = "daoyi-cloud-common"
version = "0.1.3"
edition = "2024"
description = "Common library for Daoyi Cloud"
license = "MIT"

[features]
default = ["web"]
web = ["salvo", "tokio", "tracing", "tracing-subscriber"]

[dependencies]
salvo = { version = "0.78.0", features = ["full"], optional = true }
tokio = { version = "1.44.2", features = ["macros"], optional = true }
tracing = { version = "0.1.41", optional = true }
tracing-subscriber = { version = "0.3.19", optional = true }