[package]
name = "daoyi-cloud-common"
version = "0.1.8"
edition = "2024"
description = "Common library for Daoyi Cloud"
license = "MIT"

[features]
# 完整功能
full = ["web", "gateway", "module-system"]
# 默认功能
default = []
# web功能
web = ["salvo", "tokio"]
# 系统管理功能
module-system = []
# 网关功能
gateway = []

[dependencies]
salvo = { version = "0.78.0", features = ["full"], optional = true }
tokio = { version = "1.44.2", features = ["macros"], optional = true }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }